version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_backend
    environment:
      # Railway PostgreSQL URL
      DATABASE_URL: postgresql://postgres:CeYYbEZXfCmJGJFHMNnQrMHSXqPcvXyY@postgres.railway.internal:5432/railway
      PORT: 3001
      NODE_ENV: development  # change to production if needed
    ports:
      - "3001:3001"
    command: npm run dev
    restart: unless-stopped